import Sidebar from '@/components/sidebar'
import Head from 'next/head'
// import Header from '@/components/header'
// import Footer from '@/components/footer'


export default function Layout({ children, metaTitle, metaDescription }) {
  return (
    <div className="flex min-h-screen bg-gray-50">
      {/* Sidebar */}
      <Sidebar />

      {/* Main Content */}
      <div className="flex-1">
        <Head>
          <title>To Do List - {metaTitle}</title>
          <meta name="description" content={metaDescription || "Generated by create next app"} />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* Content */}
        <main className="p-6">{children}</main>
      </div>
    </div>
  )
}

// <Image
  //                           src={`data:image/jpeg;base64,${user.profilePicture}`}
  //                           alt="Profile Picture"
  //                           layout="fill"
  //                           objectFit="cover"
  //                           />
